name: android release build

on:
  push:
    branch:
      - bixin-dev
    # Pattern matched against refs/tags
    tags:
      - onekey/*    # Push events to every tag including hierarchical tags like onekey/v2.0.5

jobs:
  android_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: |
            - /usr/local/lib/android
            - /opt/hostedtoolcache/jdk/
          key: ${{ runner.os }}-sdk
          restore-keys: ${{ runner.os }}-sdk
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: |
            - ~/.cache/pip
            - ~/.cache/chaquopy
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Setup release keystore
        run: ./.github/secrets/decrypt_keystore.sh
        env:
          IOS_CERTIFICATE_PASS: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ENCRYPT_PASS: ${{ secrets.ENCRYPT_PASS }}
      - name: build release
        run: |
          yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;android-29"
          yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} >> /dev/null
          echo 'chaquopy.license=${{ secrets.CHAQUOPY_LICENSE }}' > local.properties
          echo 'sdk.dir=/usr/local/lib/android/sdk' >> local.properties
          ./gradlew app:assembleMainNetOnekeyRelease
          ./gradlew app:assembleMainNetGooglePlayRelease
          ./gradlew app:assembleRegTestOneKeyRelease
        working-directory: android
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: push to server
        run: |
            # push release apk
            export MAINNET_APK_PATH=`ls android/app/build/outputs/apk/MainNetOnekey/release/*.apk`
            export TAG_NAME=`git describe --tags --abbrev=0`
            scp "$MAINNET_APK_PATH" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/output/
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /output && ./push_release.sh $MAINNET_APK_PATH $TAG_NAME >android_release.log"
            # push googleplay apk
            export MAINNET_APK_PATH=`ls android/app/build/outputs/apk/MainNetGooglePlay/release/*.apk`
            scp "$MAINNET_APK_PATH" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/output/
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /output && ./push_release.sh $MAINNET_APK_PATH '$TAG_NAME for googleplay' >android_release.log"
            # push regtest apk
            export REGTEST_APK_PATH=`ls android/app/build/outputs/apk/RegTestOnekey/release/*.apk`
            scp "$REGTEST_APK_PATH" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/output/
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /output && ./push.sh $REGTEST_APK_PATH '$TAG_NAME for regtest network' >android_release.log"
