name: AndroidLint

on:
  pull_request:
    branches:
      - bixin_dev
    paths:
      - .github/workflows/android-lint.yml
      - 'android/**'

jobs:
  android_lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: |
            - ~/.cache/pip
            - ~/.cache/chaquopy
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: lint check
        run: |
          yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;android-29"
          echo 'sdk.dir=/usr/local/lib/android/sdk'>local.properties
          ./gradlew app:lintRegTestDebug
        working-directory: android
      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: android/app/build/reports/lint-results-RegTestOnekeyDebug.xml
      - name: Archive lint artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: OneKey-android-lint-${{ github.sha }}
          path: |
            android/app/build/reports/lint-results-RegTestOnekeyDebug.xml
            android/app/build/reports/lint-results-RegTestOnekeyDebug.html
